- name: Init Kubernetes Master
  hosts: masters
  become: yes
  tasks:
    - name: Initialiser le cluster
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Configurer kubectl pour vagrant
      shell: |
        mkdir -p /home/vagrant/.kube
        cp /etc/kubernetes/admin.conf /home/vagrant/.kube/config
        chown -R vagrant:vagrant /home/vagrant/.kube

    - name: Installer Flannel
      become_user: vagrant
      command: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml

    - name: Récupérer commande join
      command: kubeadm token create --print-join-command
      register: join_cmd

    - name: Sauvegarder join command
      set_fact:
        join_command: "{{ join_cmd.stdout }}"
